# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9fc6754049c5285e65f65b758ea2a24c759e66267a99893b5cbd493a0de95649c6dcda41e8282ea192e5631184b6219ad3aa3e2afd8f197e04c91558e77d69b

test:
  secret_key_base: a475432ac28a6ddacd4ca77f878503c3f2ca2f190481ea180d4856aeaa13d758089495201b5436a97fc8df4657e529895bfeec6daab8173d5531636b516ac161

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
